version: '3.8'
services:
  db:
    image: postgres:15
    container_name: chat_users_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_users_db
    ports:
      - "5432:5432"